from pathlib import Path
import hashlib

DOC_A = Path("fixtures/pdfs/doc_a_60pct.pdf")
DOC_B = Path("fixtures/pdfs/doc_b_90pct.pdf")
HASHES = Path("fixtures/pdfs/HASHES.txt")
MUTATIONS_MD = Path("fixtures/mutations/MUTATIONS.md")


def test_doc_a_present_and_hash_recorded() -> None:
    assert DOC_A.exists(), "Doc A must be present"
    sha = hashlib.sha256(DOC_A.read_bytes()).hexdigest()
    recorded = HASHES.read_text()
    assert sha in recorded, f"Doc A hash {sha} not recorded in HASHES.txt"


def test_doc_b_derived_and_documented() -> None:
    assert DOC_B.exists(), "Doc B must be generated by apply_mutations.py"
    sha = hashlib.sha256(DOC_B.read_bytes()).hexdigest()
    assert sha in HASHES.read_text(), f"Doc B hash {sha} not recorded"
    md = MUTATIONS_MD.read_text()
    for required in ["TP-1", "TP-2", "TP-3", "FP-1", "FP-2", "FN-1"]:
        assert required in md, f"{required} missing from MUTATIONS.md"
